#!/usr/bin/env bash
# Toggle the Alacritty terminal between dark and light colour schemes.
#
#   theme.sh            → toggle (dark <-> light)
#   theme.sh dark       → force dark  (Gruvbox Material Dark)
#   theme.sh light      → force light (Gruvbox Material Light)
#
# Colours are written to ~/.cache/alacritty-theme.toml, which the main
# ~/.alacritty.toml imports. Alacritty live-reloads on change, so every open
# terminal updates instantly — no restart needed.
set -euo pipefail

THEME_FILE="$HOME/.cache/alacritty-theme.toml"
STATE_FILE="$HOME/.cache/theme-mode"
mkdir -p "$HOME/.cache"

mode="${1:-toggle}"
if [[ "$mode" == "toggle" ]]; then
    [[ "$(cat "$STATE_FILE" 2>/dev/null)" == "light" ]] && mode="dark" || mode="light"
fi

case "$mode" in
  dark)
    # Gruvbox Material Dark (the original scheme).
    cat > "$THEME_FILE" <<'EOF'
# Gruvbox Material Dark — generated by ~/.i3rc/scripts/theme.sh
[window]
opacity = 0.85

[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'

[colors.normal]
black   = '0x32302f'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
black   = '0x32302f'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.cursor]
cursor = '0xec5d2a'
EOF
    ;;
  light)
    # Gruvbox Material Light (Medium) — readable dark text on a light background.
    cat > "$THEME_FILE" <<'EOF'
# Gruvbox Material Light — generated by ~/.i3rc/scripts/theme.sh
[window]
opacity = 0.97

[colors.primary]
background = '0xfbf1c7'
foreground = '0x654735'

[colors.normal]
black   = '0x654735'
red     = '0xc14a4a'
green   = '0x6c782e'
yellow  = '0xb47109'
blue    = '0x45707a'
magenta = '0x945e80'
cyan    = '0x4c7a5d'
white   = '0xa89984'

[colors.bright]
black   = '0xa89984'
red     = '0xc14a4a'
green   = '0x6c782e'
yellow  = '0xb47109'
blue    = '0x45707a'
magenta = '0x945e80'
cyan    = '0x4c7a5d'
white   = '0x654735'

[colors.cursor]
cursor = '0xc35e0a'
EOF
    ;;
  *)
    echo "usage: theme.sh [toggle|dark|light]" >&2
    exit 1
    ;;
esac

echo "$mode" > "$STATE_FILE"
command -v notify-send >/dev/null 2>&1 && notify-send -t 1500 "Terminal theme" "Switched to ${mode} mode"
